personal_portfolio_project/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.blog_detail, name='blog_detail'),
]

personal_portfolio_project/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_portfolio_project/portfolio/urls.py
from django.urls import path

personal_portfolio_project/blog/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    timestamp = models.DateField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return self.title

personal_portfolio_project/portfolio/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)
    image = models.ImageField(upload_to='portfolio/images/', blank=True)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

personal_portfolio_project/blog/views.py
from django.shortcuts import render, get_object_or_404

from .models import *

# Create your views here.


def all_blogs(request):
    blogs = Blog.objects.order_by('-timestamp')
    context = {
        'blogs': blogs,
    }
    return render(request, 'blog/all_blogs.html', context)


def blog_detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    context = {
        'blog': blog,
    }
    return render(request, 'blog/blog_detail.html', context)

personal_portfolio_project/personal_portfolio/views.py
from django.shortcuts import render


def home(request):
    context = {}
    return render(request, 'home.html', context)

personal_portfolio_project/portfolio/views.py
from django.shortcuts import render

# Create your views here.

personal_portfolio_project/blog/templates/blog/all_blogs.html
{% extends 'main.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1><strong>This is my blog</strong></h1>
            <h2>I have written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h2>
        </div>
    </div>
    <div class="row">
    {% for blog in blogs %}
        <div class="col-md-12">
            <a href="{% url 'blog:blog_detail' blog.pk %}"><h3>{{ blog.title }}</h3></a>
            <p>{{ blog.timestamp }}</p>
            <p>{{ blog.content|truncatechars:100 }}</p>
        </div>
    {% endfor %}
    </div>
</div>

{% endblock content %}

personal_portfolio_project/blog/templates/blog/blog_detail.html
{% extends 'main.html' %}

{% block content %}

<div class='container'>
    <h1>{{ blog.title }}</h1>
    <h2>{{ blog.timestamp }}</h2>
    <p>{{ blog.content }}</p>
</div> 

{% endblock content %}

personal_portfolio_project/templates/home.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<h1>Personal Portfolio</h1>

{% endblock content %}

personal_portfolio_project/templates/main.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="icon" href="{% static 'portfolio/logo.png' %}" type = "image/x-icon"/>

    <title>Huy Nguyen</title>
  </head>
  <body>
    
    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>